package postgres

var schema = `
CREATE OR REPLACE FUNCTION trigger_update_date()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = CURRENT_DATE;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TABLE machines (
	id SERIAL PRIMARY KEY,
	uri VARCHAR(2048) UNIQUE NOT NULL,
	access_key VARCHAR(2048) NOT NULL,
	name VARCHAR(248) NOT NULL,
	created_at DATE NOT NULL DEFAULT CURRENT_DATE,
	updated_at DATE NOT NULL DEFAULT CURRENT_DATE
);


CREATE TRIGGER update_date
BEFORE UPDATE ON machines
FOR EACH ROW
EXECUTE PROCEDURE trigger_update_date();
`
